spring:
  data:
    mongodb:
      uri: mongodb://用户名:密码@localhost:27017/数据库
    redis:
      host: localhost
      port: 6379
      password: 密码
  rabbitmq:
    host: localhost
    port: 5672
    username: 用户名
    password: 密码
    listener:
      simple:
        retry:
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）
          enabled: true
  # 邮箱 配置
  mail:
    host: smtp.163.com
    username: 用户名
    password: 密码
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory